name: Selenic Analysis

on:
  push:
    branches:
      - main

jobs:
  run-selenic:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Selenium Tests with Selenic Agent
        run: |
          mvn test ^
          -DargLine="-javaagent:D:\parasoft_selenic_2026.1.0\selenic_agent.jar=captureDOM=true,screenshot=failures,selfHealing=true,createAPITests=false" ^
          -Dwebdriver.chrome.driver="D:\chromedriver-win64\chromedriver-win64\chromedriver.exe"
        shell: cmd

      - name: Run Selenic Analyzer
        run: |
          java -jar "D:\parasoft_selenic_2026.1.0\selenic_analyzer.jar" -source . -report "D:\tias\selenic_report"
        shell: cmd
