name: Jira Trigger

on:
  repository_dispatch:
    types:
      - jira-assigned

jobs:
  run-workitem-tests:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get Jira Issue Key
        shell: powershell
        run: |
          $issueKey = "${{ github.event.client_payload.issueKey }}"
          Set-Content issue.txt $issueKey
          Write-Host "Issue Key: $issueKey"

      - name: Find Matching WorkItem Classes
        shell: powershell
        run: |

          $issueKey = (Get-Content issue.txt).Trim()

          if (Test-Path "matching-classes.txt") {
            Remove-Item "matching-classes.txt"
          }

          Get-ChildItem `
            -Path "src/test/java" `
            -Recurse `
            -Filter "*.java" |

          ForEach-Object {

            $content = Get-Content $_.FullName -Raw

            if ($content.Contains('id="' + $issueKey + '"')) {

              Write-Host "Found: $($_.BaseName)"

              Add-Content "matching-classes.txt" $_.BaseName
            }
          }

          if (!(Test-Path "matching-classes.txt")) {

            throw "No test classes found for $issueKey"

          }

          Write-Host ""
          Write-Host "====================================="
          Write-Host "MATCHING CLASSES"
          Write-Host "====================================="

          Get-Content "matching-classes.txt"

      - name: Detect New Tests
        shell: powershell
        run: |
          .\scripts\Detect-NewTests.ps1

      - name: Execute New Tests
        shell: powershell
        run: |

          if (!(Test-Path tests-to-run.txt)) {

            Write-Host "No new tests detected."
            exit 0
          }

          $tests = Get-Content tests-to-run.txt

          foreach ($test in $tests) {

            Write-Host "Running $test"

            mvn test `
              "-Dtest=$test" `
              "-DargLine=-javaagent:D:\parasoft_selenic_2026.1.0\selenic_agent.jar=captureDOM=true,screenshot=failures,selfHealing=true,createAPITests=false" `
              "-Dwebdriver.chrome.driver=D:\chromedriver-win64\chromedriver-win64\chromedriver.exe"

            if ($LASTEXITCODE -eq 0) {
              Add-Content execution-status.txt "$test : PASSED"
            }
            else {
              Add-Content execution-status.txt "$test : FAILED"
            }
          }
    
      - name: Debug Files
        shell: powershell
        run: |

          Write-Host "Current directory:"
          Get-Location

          Write-Host "History exists:"
          Test-Path .history/executed-classes.json

          Write-Host "Tests file exists:"
          Test-Path tests-to-run.txt

          if (Test-Path tests-to-run.txt) {
            Get-Content tests-to-run.txt
          }



     
      - name: Update Execution History
        if: success()
        shell: powershell
        run: |
          .\scripts\Update-History.ps1

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload Selenic Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenic-reports
          path: D:\tias\selenic_report

      - name: Update Jira
        if: always()
        shell: powershell
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          GITHUB_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          .\scripts\Update-Jira.ps1
