name: Jira Trigger

on:
  repository_dispatch:
    types:
      - jira-assigned

jobs:

  run-workitem-tests:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Jira Issue Key
        shell: powershell
        run: |

          $issueKey = "${{ github.event.client_payload.issueKey }}"

          Write-Host "Issue Key: $issueKey"

          $issueKey | Out-File issue.txt

      - name: Find Matching WorkItem Classes
        shell: powershell
        run: |

          $issueKey = Get-Content issue.txt

          Remove-Item tests-to-run.txt -ErrorAction SilentlyContinue

          Get-ChildItem `
            -Path "src/test/java" `
            -Recurse `
            -Filter "*.java" |

          ForEach-Object {

              $content = Get-Content $_.FullName -Raw

              if ($content -match "id\s*=\s*`"$issueKey`"") {

                  Write-Host "Found: $($_.BaseName)"

                  Add-Content tests-to-run.txt $_.BaseName
              }
          }

          if (!(Test-Path tests-to-run.txt)) {
              throw "No test classes found for $issueKey"
          }

          Get-Content tests-to-run.txt

      - name: Execute Matching Tests
        shell: powershell
        run: |

          Remove-Item execution-status.txt -ErrorAction SilentlyContinue

          $tests = Get-Content tests-to-run.txt

          foreach ($test in $tests) {

              Write-Host ""
              Write-Host "Running $test"

              mvn test `
                "-Dtest=$test" `
                "-DargLine=-javaagent:D:\parasoft_selenic_2026.1.0\selenic_agent.jar=captureDOM=true,screenshot=failures,selfHealing=true,createAPITests=false" `
                "-Dwebdriver.chrome.driver=D:\chromedriver-win64\chromedriver-win64\chromedriver.exe"

              if ($LASTEXITCODE -eq 0) {
                  Add-Content execution-status.txt "$test : PASSED"
              }
              else {
                  Add-Content execution-status.txt "$test : FAILED"
              }
          }

      - name: Show Results
        shell: powershell
        run: |

          Write-Host ""
          Write-Host "==== EXECUTION RESULTS ===="

          if (Test-Path execution-status.txt) {
              Get-Content execution-status.txt
          }

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload Selenic Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenic-reports
          path: D:\tias\selenic_report

      - name: Upload Execution Status
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-status
          path: execution-status.txt
`
