name: Execute New Test Classes

on:
  push:
    branches:
      - main

jobs:
  execute-new-tests:

    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find Changed Files
        shell: cmd
        run: |
          git diff --name-only HEAD~1 HEAD > changedfiles.txt

          echo ==================================
          echo CHANGED FILES
          echo ==================================

          type changedfiles.txt

      - name: Find Test Classes
        shell: cmd
        run: |
          findstr /i "Tests.java" changedfiles.txt > newtests.txt

          if errorlevel 1 (
            echo No new test classes found.
            exit /b 0
          )

          echo ==================================
          echo TEST CLASSES FOUND
          echo ==================================

          type newtests.txt

      - name: Execute New Test Classes
        shell: cmd
        run: |

          for /f %%i in (newtests.txt) do (

            for %%j in ("%%i") do (

              echo.
              echo ==================================
              echo Processing %%~nj
              echo ==================================

              mvn test ^
              -Dtest=%%~nj ^
              -DargLine="-javaagent:D:\parasoft_selenic_2026.1.0\selenic_agent.jar=captureDOM=true,screenshot=failures,selfHealing=true,createAPITests=false" ^
              -Dwebdriver.chrome.driver="D:\chromedriver-win64\chromedriver-win64\chromedriver.exe"

            )
          )
