name: Execute New Test Classes

on:
  push:
    branches:
      - main

jobs:
  execute-new-tests:

    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find Changed Files
        shell: cmd
        run: |
          git diff --name-only HEAD~1 HEAD > changedfiles.txt

          echo ==================================
          echo CHANGED FILES
          echo ==================================

          type changedfiles.txt

      - name: Find Test Classes
        shell: cmd
        run: |
          findstr /i "Tests.java" changedfiles.txt > newtests.txt

          if errorlevel 1 (
            echo ==================================
            echo NO NEW TEST CLASSES FOUND
            echo ==================================
            exit /b 0
          )

          echo ==================================
          echo TEST CLASSES FOUND
          echo ==================================

          type newtests.txt

      - name: Display Tests
        shell: cmd
        run: |
          if exist newtests.txt (
            echo ==================================
            echo DETECTED TEST FILES
            echo ==================================
            type newtests.txt
          ) else (
            echo No new test classes found.
          )
